# In case the main build script fails, this script allows a manual release of the docker image,
# assuming the binaries are uploaded to the release.
name: Release Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  build-docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ github.event.inputs.version }}
          tags: |
            deno911/deno:${{ github.event.inputs.version }}
            deno911/deno:latest
